name: quivira
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - heyoka.py
  - numpy
  - scipy
  - ipython
  - sphinx
  - furo
  - nbsphinx
  - pandoc
  - sphinx-copybutton
  - sphinx-design
  - ipykernel
  - jupyter
  - pip:
      - -e .